# Site settings
title: Int3ractive
image: img/default-bg.jpg
email: trongthanh@gmail.com
description: "The writing playground and technical journey of Trần Trọng Thanh, front-end architect, js developer, husband and father, from Ho Chi Minh city, Vietnam"
baseurl: ""
url: "https://int3ractive.com"
twitter_username: trongthanh
github_username:  trongthanh
facebook_username: trongthanh
linkedin_username: trongthanh
googleplus_userid: +TrọngThanhTrần
gaid: UA-4430452-4
disqus_site_id: conansblog

# SEO & Social networks
seo_title: Int3ractive - Front End, JavaScript, CSS architect, workflow and guides in English & Vietnamese
author: Thanh Tran (int3ractive.com)
logo: img/favicon.png
twitter:
  username: trongthanh

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
permalink: :year/:month/:title.html
paginate: 10
exclude: ["README.md", "css/**/*"]
keep_files: ["flash","javascript"]
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji

